"""Tests for scripts/hub_alert.py - the fleet's alert wrapper.

SGR-11 pins the dedup contract (one open issue per key) and the body
contract: counts and redacted locations, never a matched value. The
extraction is by FIELD NAME - `state`, `uncovered`, and
`locations[].rule/path/line/commit` only - so a report that carries a
planted `Secret` field cannot leak it into the issue.

This is T-31's cousin and is recorded as part of the Sprint 1 mutation
proofs (secret-gate-rollout).

Dual-runnable like its siblings: pytest collects test_*;
`python3 tests/test_hub_alert.py` runs them too.
"""
import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "scripts" / "hub_alert.py"

# The fields the issue body is allowed to quote out of a finding. Anything
# else - including a field literally named `Secret` - must not survive.
SAFE_FIELDS = {"rule", "path", "line", "commit"}

# Planted secrets. Never assert on a live credential; a sentinel string is
# enough because the assertion is "this string does not appear in the body".
PLANTED_SECRET = "OUR-CANARY-SECRET-DO-NOT-LEAK"


def write_report(tmp_path, repos, *, report_kw=None):
    report = {
        "declared": 12,
        "scanned": 11,
        "states": {"clean": 9, "findings": 1, "unfetchable": 1, "unscannable": 0},
        "repos": repos,
    }
    if report_kw:
        report.update(report_kw)
    path = tmp_path / "fleet-report.json"
    path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    return path


def run(*argv, env=None):
    return subprocess.run(
        [sys.executable, str(SCRIPT), *map(str, argv)],
        capture_output=True,
        text=True,
        env=env,
    )


# --- T-31-cousin: a planted value must not leak ------------------------------


def test_a_planted_secret_field_is_dropped_by_name(tmp_path):
    """The one test that exists because the failure mode is silent.

    `report.json` is generated by the gate, whose record() already
    filters by field name. hub_alert.py reads the same report one step
    later. If either side stops filtering, the planted `Secret` arrives in
    a GitHub issue body where a human reads it forever. The sweep can be
    rerun; the issue cannot be un-seen.
    """
    report = write_report(
        tmp_path,
        [
            {
                "name": "TheArchitectit/plexus-debug-ui",
                "url": "https://github.com/TheArchitectit/plexus-debug-ui",
                "state": "findings",
                "uncovered": 1,
                "locations": [
                    {
                        "rule": "generic-api-key",
                        "path": "src/app.js",
                        "line": 42,
                        "commit": "abc123ef",
                        "Secret": PLANTED_SECRET,
                        "Match": PLANTED_SECRET,
                    }
                ],
            },
            {
                "name": "TheArchitectit/LobsterWars",
                "url": "https://github.com/TheArchitectit/LobsterWars",
                "state": "unfetchable",
                "uncovered": 0,
                "reason": "could not fetch: Authentication failed",
            },
        ],
    )
    res = run("--key", "secret_fleet_sweep", "--report", report,
              "--dry-run")
    assert res.returncode == 0, (res.returncode, res.stdout, res.stderr)
    body = res.stdout
    assert PLANTED_SECRET not in body, body
    assert "generic-api-key" in body, body
    assert "src/app.js" in body, body
    assert "abc123ef" in body, body
    # Safe fields DID make it through - filtering kept, not discarded whole.
    kept = {"rule", "path", "commit"}
    assert all(k in body for k in kept), body


def test_only_the_documented_fields_survive_extraction(tmp_path):
    """The filter is name-driven so a future edit cannot quietly widen it
    just because someone added a key. Assert the set of keys that survive
    is exactly SAFE_FIELDS.
    """
    sys.path.insert(0, str(REPO_ROOT))
    from scripts.hub_alert import extract_summary  # noqa: E402

    report = {
        "declared": 1,
        "scanned": 1,
        "states": {"findings": 1},
        "repos": [
            {
                "name": "TheArchitectit/a",
                "state": "findings",
                "uncovered": 1,
                "locations": [
                    {
                        "rule": "hospital",
                        "path": "grep.md",
                        "line": 9,
                        "commit": "deadbeef",
                        "Secret": PLANTED_SECRET,
                        "Match": PLANTED_SECRET,
                        "Entropy": "4.2",
                    }
                ],
            }
        ],
    }
    _summary, _uncovered, _scanned, safe = extract_summary(report)
    assert len(safe) == 1, safe
    assert set(safe[0].keys()) == SAFE_FIELDS, safe[0]
    assert PLANTED_SECRET not in json.dumps(safe)


def test_fields_added_later_silently_do_not_widen_the_filter():
    """A future report-edit that adds a `keys` list next to a finding is a
    value-holder wearing a helpful-sounding name. The extractor drops it
    without comment. This test is the regression tripwire on that one rule.
    """
    sys.path.insert(0, str(REPO_ROOT))
    from scripts.hub_alert import extract_summary  # noqa: E402

    report = {
        "declared": 1,
        "scanned": 1,
        "states": {"findings": 1},
        "repos": [
            {
                "state": "findings",
                "uncovered": 1,
                "locations": [
                    {
                        "rule": "pat",
                        "path": "x.env",
                        "line": 1,
                        "commit": "1",
                        "keys": [PLANTED_SECRET],
                        "present": True,
                    }
                ],
            }
        ],
    }
    _s, _u, _sc, safe = extract_summary(report)
    assert set(safe[0]) == SAFE_FIELDS, safe[0]
    assert PLANTED_SECRET not in json.dumps(safe)


# --- body shape --------------------------------------------------------------


def test_summary_carries_states_and_counts_only(tmp_path):
    report = write_report(
        tmp_path,
        [
            {
                "name": "TheArchitectit/a",
                "state": "clean",
                "uncovered": 0,
                "locations": [],
            },
            {
                "name": "TheArchitectit/b",
                "state": "findings",
                "uncovered": 2,
                "locations": [
                    {
                        "rule": "aws",
                        "path": "cfg.toml",
                        "line": 11,
                        "commit": "cff1",
                    },
                    {
                        "rule": "aws",
                        "path": "cfg.prod.toml",
                        "line": 3,
                        "commit": "cff2",
                    },
                ],
            },
        ],
    )
    res = run("--key", "k", "--report", report, "--dry-run")
    assert res.returncode == 0
    out = res.stdout
    assert "declared=12" in out
    assert "uncovered_total=2" in out
    assert "clean=9" in out and "findings=1" in out
    assert "aws" in out and "cfg.toml:11" in out and "cfg.prod.toml:3" in out
    assert "cff1" in out and "cff2" in out
    # No fixture-quoteable shape of a token:
    assert not any(tok in out for tok in ("SECRET", "TOKEN=", "Bearer "))


def test_an_emitted_empty_reports_says_not_clean(tmp_path):
    """An empty `locations` list is not a clean fleet statement - the
    body must not read that way either. The wording says what was missing
    rather than satisfying a human's first glance.
    """
    report = write_report(
        tmp_path,
        [{"name": "TheArchitectit/private-thing", "state": "unfetchable",
          "uncovered": 0, "locations": []}],
    )
    res = run("--key", "k", "--report", report, "--dry-run")
    body = res.stdout
    assert "no redacted locations" in body, body
    assert "unfetchable" in body or "unscannable" in body, body


# --- invocation -------------------------------------------------------------


def test_detail_exit_shape(tmp_path):
    """A non-dry --detail without a token is a missing-credential exit 3,
    not a spurious raise_alert that would fail every offline dev build.
    """
    res = run("--key", "required_check_red_on_main", "--detail", "seed failed")
    assert res.returncode == 3, (res.returncode, res.stderr)
    assert "token" in res.stderr.lower(), res.stderr


def test_bad_report_is_a_refusal_not_a_silent_empty_body(tmp_path):
    """A truncated or malformed report is closer to the Exit 2 family:
    the alert was not reliably extractable, so nothing may be asserted.
    Shows up as 3 (bad input) with an operator-visible name of the file.
    """
    bad = tmp_path / "broken.json"
    bad.write_text("{not json", encoding="utf-8")
    res = run("--key", "k", "--report", bad, "--dry-run")
    assert res.returncode == 3, (res.returncode, res.stderr)
    assert "broken.json" in res.stderr, res.stderr


def test_report_and_detail_together_is_a_bad_invocation():
    res = run("--key", "k", "--report", "x", "--detail", "y")
    assert res.returncode != 0
    assert "report" in res.stderr.lower() or "detail" in res.stderr.lower()


def test_neither_report_nor_detail_is_a_bad_invocation():
    res = run("--key", "k")
    assert res.returncode != 0
    assert "report" in res.stderr.lower() or "detail" in res.stderr.lower()


def test_dry_run_without_report_is_refused(tmp_path):
    res = run("--key", "k", "--detail", "seed failed", "--dry-run")
    assert res.returncode != 0
    assert "dry-run" in res.stderr.lower() or "report" in res.stderr.lower()


def test_the_script_is_python_and_executable():
    """CI calls it as `python3 scripts/hub_alert.py`, so the shebang is
    documentation and the mode is what a `./hub_alert.py` reader expects.
    The fix-commit precedent in this repo is that a shell helper that
    shipped 0644 looked committed and then wasn't runnable - the test
    exists so that does not silently repeat here.
    """
    assert SCRIPT.exists()
    text = SCRIPT.read_text(encoding="utf-8")
    assert text.startswith("#!/usr/bin/env python3")


if __name__ == "__main__":
    import pytest as _pytest

    sys.exit(_pytest.main([__file__, "-q"]))